-- Create carestaff schema if not exists
CREATE SCHEMA IF NOT EXISTS carestaff;

-- Create users table inside carestaff schema
CREATE TABLE IF NOT EXISTS carestaff.STAFF (
    ID SERIAL PRIMARY KEY,
    STAFF_ID VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ROLE VARCHAR(100) NOT NULL,
    SHIFT_PREFERENCE VARCHAR(100) NOT NULL,
    CONTACT_NO BIGINT NOT NULL,
    CREATED_BY VARCHAR(100),
    MODIFIED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carestaff.shift (
    ID SERIAL PRIMARY KEY,
    SHIFT_DATE DATE NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    TOTAL_CAPACITY INTEGER,
    AVAILABLE_CAPACITY INTEGER,
    CREATED_BY VARCHAR(100),
    MODIFIED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP
);

CREATE TABLE IF NOT EXISTS carestaff.STAFFSHIFTMAPPING (
    ID SERIAL PRIMARY KEY,
    STAFF INTEGER NOT NULL,
    SHIFT INTEGER NOT NULL,
    IS_DELETED INTEGER DEFAULT 0,
    CREATED_BY VARCHAR(100),
    MODIFIED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_STAFF FOREIGN KEY (STAFF) REFERENCES carestaff.STAFF(id),
    CONSTRAINT FK_SHIFT FOREIGN KEY (SHIFT) REFERENCES carestaff.SHIFT(id)
);

CREATE TABLE IF NOT EXISTS carestaff.ATTENDANCE (
    ID SERIAL PRIMARY KEY,
    STAFF_SHIFT_MAPPING_ID INTEGER NOT NULL,
    IS_PRESENT INTEGER DEFAULT 0,
    CREATED_BY VARCHAR(100),
    MODIFIED_BY VARCHAR(100),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    CONSTRAINT FK_STAFFSHIFTMAPPING FOREIGN KEY (STAFF_SHIFT_MAPPING_ID) REFERENCES carestaff.STAFFSHIFTMAPPING(id)
);